version: "3.2"

services:
#Mysql Container
  mysql:
    image: mysql:5.7.23
    container_name: mysql
    hostname: mysql
    volumes:
      - /var/lib/mysql:/var/lib/mysql
    env_file:
      - ./mysql.env
    environment:
      - TIMEZONE=Europe/Paris
    restart: always

#GLPI Container
  glpi:
    image: wemr/glpi
    container_name : glpi
    hostname: glpi
    ports:
      - "80:80"
    depends_on:
      - mysql
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /var/www/html/glpi/:/var/www/html/glpi
    environment:
      - TIMEZONE=Europe/Paris
    restart: always
